[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = { eth = "https://eth-sepolia.g.alchemy.com/v2/mwHkM74gwkO6kdWQKCYBRWdbDUnhZB7E", arb = "https://arb-sepolia.g.alchemy.com/v2/mwHkM74gwkO6kdWQKCYBRWdbDUnhZB7E", zksync = "https://sepolia.era.zksync.dev" }

remappings = [
    "@chainlink/contracts-ccip/contracts/libraries/=lib/chainlink-local/lib/chainlink-ccip/chains/evm/contracts/libraries/",
    "@chainlink/contracts-ccip/src/v0.8/vendor/openzeppelin-solidity/v4.8.3/contracts/=lib/chainlink-local/lib/chainlink-evm/contracts/src/v0.8/vendor/openzeppelin-solidity/v4.8.3/contracts/",
    "@chainlink/contracts-ccip/src/v0.8/ccip/=lib/chainlink-local/lib/chainlink-ccip/chains/evm/contracts/",
    "@ccip/contracts/src/v0.8/ccip/=lib/chainlink-local/lib/chainlink-ccip/chains/evm/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink-local/=lib/chainlink-local/"
]
